In [1]:
from data_collection.data_adapters import DatabentoGenericAdapter
from dotenv import load_dotenv
from pathlib import Path
import os
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
load_dotenv()
pl.enable_string_cache()

CACHE_DIR = Path.cwd().resolve().parents[0] / "data" / "dbn_cache" / "generic"
adapter = DatabentoGenericAdapter(os.getenv("DATABENTO-API-KEY"), CACHE_DIR)

print(f"CACHE_DIR: {CACHE_DIR}")
# Clear the cache if needed
# adapter.clear_cache()

with open("../universe.txt", "r") as f:
    UNIVERSE = [line.strip() for line in f]
START = "2023-06-01"
END = "2025-06-01"
DATASET = "XNAS.ITCH"

df_bars = (
    adapter.scan_data(
        tickers="ALL_SYMBOLS",
        start_date=START,
        end_date=END,
        dataset=DATASET,
        schema="ohlcv-1d"
    )
    .select(["ts_event", "symbol", "close"])
    .with_columns(
        pl.col("symbol").cast(pl.Categorical)
    )
    .filter(
        pl.col("symbol").is_in(UNIVERSE)
    )
    .sort(["ts_event", "symbol"])
)


daily_ret = (
    df_bars
    .with_columns(
        pl.col("close").pct_change().over("symbol").alias("ret")
    )
    .pivot(
        on="symbol",
        on_columns=UNIVERSE,
        index="ts_event",
        values="ret"
    )
)

daily_ret = daily_ret.collect(engine="streaming")
daily_ret

CACHE_DIR: /Users/michaelcusack-nelkin/GitHub/Summer_Research_2026/data/dbn_cache/generic
[GenericAdapter] scan_parquet: 548cfb7cc98703d7d8a8a14fe79dfe1a.parquet

shape: (501, 2_001)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ts_event  ┆ NVDA      ┆ SPY       ┆ TSLA      ┆ … ┆ TGNA      ┆ FIZZ      ┆ MAC       ┆ ANGL     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ datetime[ ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│ ns, UTC]  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2023-06-0 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-06-0 ┆ -0.018389 ┆ 0.014265  ┆ 0.028723  ┆ … ┆ 0.029728  ┆ 0.014582  ┆ 0.08746   ┆ 0.007356 │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-06-0 ┆ -0.00599  ┆ -0.003224 ┆ 0.010242  ┆ … ┆ -0.004914 ┆ -0.02004  ┆ -0.005329 ┆ -0.01058 │
│ 5         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-06-0 ┆ -0.005385 ┆ 0.004313  ┆ 0.041711  ┆ … ┆ -0.009259 ┆ -0.008469 ┆ 0.05358   ┆ 0.012177 │
│ 6         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-06-0 ┆ -0.026167 ┆ -0.004341 ┆ -0.008755 ┆ … ┆ 0.010592  ┆ 0.005417  ┆ 0.046694  ┆ 0.002552 │
│ 7         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-05-2 ┆ -0.012422 ┆ -0.007168 ┆ -0.006692 ┆ … ┆ -0.004788 ┆ -0.009243 ┆ -0.022339 ┆ -0.00140 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-05-2 ┆ 0.033618  ┆ 0.021295  ┆ 0.081112  ┆ … ┆ 0.023151  ┆ 0.006143  ┆ 0.034946  ┆ 0.007744 │
│ 7         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-05-2 ┆ 0.042702  ┆ 0.008912  ┆ -0.007837 ┆ … ┆ -0.01675  ┆ -0.005654 ┆ 0.025     ┆ 0.000699 │
│ 8         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-05-2 ┆ -0.025251 ┆ -0.013929 ┆ -0.026304 ┆ … ┆ 0.009265  ┆ 0.019786  ┆ 0.026924  ┆ 0.001745 │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-05-3 ┆ -0.023801 ┆ 0.00017   ┆ -0.026761 ┆ … ┆ -0.010364 ┆ 0.008698  ┆ -0.002159 ┆ 0.0      │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [2]:
from scipy.signal import find_peaks
for col in daily_ret.columns[1:]:
    peaks=find_peaks(daily_ret[col].abs(), threshold=0.30)
    if len(peaks[0]) != 0:
        # daily_ret[col].iloc[peaks[0][0]-10: peaks[0][0]+10].plot()
        print(col)

# Seems like no CAX mistakes?

NVDA
AVGO
SMCI
MSTR
LRCX
PANW
SOXL
SOXX
SQQQ
NVDL
DXCM
WMT
ODFL
CTAS
TSCO
RIVN
CPRT
FAST
NVO
ANET
CMG
CELH
CVNA
SOXS
IJH
IGV
DG
SRPT
COO
GTLB
DECK
TMF
APH
VKTX
WSM
VXX
UVXY
INSM
SH
QID
SIRI
PSQ
CYTK
SRE
SPXU
ETR
TTEK
PCVX
TGTX
WST
SCHD
BBIO
X
CONL
RYAAY
IREN
ASTS
TECL
CNQ
COKE
SDOW
AAON
TSLQ
LABU
QDEL
IOVA
SVXY
BOIL
EXLS
NWL
HUT
RXRX
SWTX
UNG
SYM
CORT
WOLF
ACAD
LBTYK
AAP
WULF
NVAX
BITX
AAOI
SCHF
SCHG
CRNX
HTZ
IMVT
LBTYA
GL
WRB
RDFN
TMV
PDCO
AKRO
GME
TPL
FL
BE
ACMR
PTGX
HUBG
NVCR
KOLD
DYN
SONY
APLD
VIXY
MTH
OMCL
PATK
SCHX
CPRI
VERA
RUSHA
NVDS
RXST
ODP
DOCS
RCKT
GERN
JANX
PCRX
ARVN
TVTX
SAGE
DPST
SMMT
DUST
GPCR
MLTX
SLNO
SSRM
KROS
CABO
UVIX
BTBT
DRVN
HEES
NEO
ROOT
YANG
CDNA
AMC
GRPN
DV
VICR
MLI
IYT
IRON
SRRK
SAVA
ETNB
EWTX
XMTR
CRVL
KURA
VIR
BYND
YPF
TECS
DLO
INDI
SCHP
SARK
FNGD
RILY
BTDR
LAZR
NVEE
COMM
XLG
JDST
HAIN
IRBT
JOBY
PGY
RLAY
QS
PRAX
NVTS
REPL
EDIT
SCHB
BITI
RLI
LQDA
SCHR

In [3]:
df_bars.collect(engine="streaming")

shape: (1_001_387, 3)
┌─────────────────────────┬────────┬────────┐
│ ts_event                ┆ symbol ┆ close  │
│ ---                     ┆ ---    ┆ ---    │
│ datetime[ns, UTC]       ┆ cat    ┆ f64    │
╞═════════════════════════╪════════╪════════╡
│ 2023-06-01 00:00:00 UTC ┆ A      ┆ 116.0  │
│ 2023-06-01 00:00:00 UTC ┆ AA     ┆ 32.75  │
│ 2023-06-01 00:00:00 UTC ┆ AAL    ┆ 14.66  │
│ 2023-06-01 00:00:00 UTC ┆ AAOI   ┆ 2.21   │
│ 2023-06-01 00:00:00 UTC ┆ AAON   ┆ 87.67  │
│ …                       ┆ …      ┆ …      │
│ 2025-05-30 00:00:00 UTC ┆ ZM     ┆ 80.52  │
│ 2025-05-30 00:00:00 UTC ┆ ZS     ┆ 275.5  │
│ 2025-05-30 00:00:00 UTC ┆ ZTO    ┆ 17.59  │
│ 2025-05-30 00:00:00 UTC ┆ ZTS    ┆ 168.63 │
│ 2025-05-30 00:00:00 UTC ┆ ZWS    ┆ 36.16  │
└─────────────────────────┴────────┴────────┘