### TEsting functionalities

In [4]:
from data_collection.data_adapters import DatabentoGenericAdapter
from dotenv import load_dotenv
from pathlib import Path
import os
load_dotenv()

CACHE_DIR = Path.cwd().resolve().parents[1] / "data" / "dbn_cache" / "generic"
adapter = DatabentoGenericAdapter(os.getenv("DATABENTO-API-KEY"), CACHE_DIR)
df_imbalance, map_imbalance = await adapter.get_data(
    tickers=["AMZN"],
    start_date="2026-04-19",
    end_date="2026-05-19",
    dataset="XNAS.ITCH",
    schema="Imbalance"
)

map_imbalance = {v: k for k,v in map_imbalance.items()}

print(f"File size (gb): {df_imbalance.estimated_size('gb'):.2f}")

df_imbalance.head()

[GenericAdapter] Parquet cache hit: 09a704dcc7d1071e299eb6af360b5c58.parquet
File size (gb): 0.00

shape: (5, 25)
┌────────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬────────┐
│ ts_recv    ┆ ts_event   ┆ rtype ┆ publisher_ ┆ … ┆ num_extens ┆ unpaired_s ┆ significan ┆ symbol │
│ ---        ┆ ---        ┆ ---   ┆ id         ┆   ┆ ions       ┆ ide        ┆ t_imbalanc ┆ ---    │
│ datetime[n ┆ datetime[n ┆ u8    ┆ ---        ┆   ┆ ---        ┆ ---        ┆ e          ┆ str    │
│ s, UTC]    ┆ s, US/East ┆       ┆ u16        ┆   ┆ u8         ┆ str        ┆ ---        ┆        │
│            ┆ ern]       ┆       ┆            ┆   ┆            ┆            ┆ str        ┆        │
╞════════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪════════╡
│ 2026-04-20 ┆ 2026-04-20 ┆ 20    ┆ 2          ┆ … ┆ 0          ┆ N          ┆ ~          ┆ AMZN   │
│ 19:50:00.0 ┆ 15:50:00.0 ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 29036342 … ┆ 28867811 … ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 2026-04-20 ┆ 2026-04-20 ┆ 20    ┆ 2          ┆ … ┆ 0          ┆ N          ┆ ~          ┆ AMZN   │
│ 19:50:10.0 ┆ 15:50:10.0 ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 23938255 … ┆ 23771476 … ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 2026-04-20 ┆ 2026-04-20 ┆ 20    ┆ 2          ┆ … ┆ 0          ┆ N          ┆ ~          ┆ AMZN   │
│ 19:50:20.0 ┆ 15:50:20.0 ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 27894258 … ┆ 27726664 … ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 2026-04-20 ┆ 2026-04-20 ┆ 20    ┆ 2          ┆ … ┆ 0          ┆ N          ┆ ~          ┆ AMZN   │
│ 19:50:30.0 ┆ 15:50:30.0 ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 02304547 … ┆ 02137063 … ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 2026-04-20 ┆ 2026-04-20 ┆ 20    ┆ 2          ┆ … ┆ 0          ┆ N          ┆ ~          ┆ AMZN   │
│ 19:50:40.0 ┆ 15:50:40.0 ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
│ 21985493 … ┆ 21818372 … ┆       ┆            ┆   ┆            ┆            ┆            ┆        │
└────────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴────────┘

In [3]:
df_bars, map_bars = await adapter.get_data(
    tickers=["AMZN"],
    start_date="2026-04-19",
    end_date="2026-05-19",
    dataset="XNAS.ITCH",
    schema="ohlcv-1s"
)

map_bars = {v: k for k,v in map_bars.items()}

print(f"File size (gb): {df_bars.estimated_size('gb'):.2f}")

df_bars.head()

[GenericAdapter] Parquet cache hit: 23cd3cce979ab29796e47e1468bf5553.parquet
File size (gb): 0.02

shape: (5, 10)
┌──────────────┬───────┬──────────────┬───────────────┬───┬────────┬────────┬────────┬────────┐
│ ts_event     ┆ rtype ┆ publisher_id ┆ instrument_id ┆ … ┆ low    ┆ close  ┆ volume ┆ symbol │
│ ---          ┆ ---   ┆ ---          ┆ ---           ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[ns, ┆ u8    ┆ u16          ┆ u32           ┆   ┆ f64    ┆ f64    ┆ u64    ┆ str    │
│ US/Eastern]  ┆       ┆              ┆               ┆   ┆        ┆        ┆        ┆        │
╞══════════════╪═══════╪══════════════╪═══════════════╪═══╪════════╪════════╪════════╪════════╡
│ 2026-04-20   ┆ 32    ┆ 2            ┆ 853           ┆ … ┆ 249.23 ┆ 249.25 ┆ 705653 ┆ AMZN   │
│ 09:30:00 EDT ┆       ┆              ┆               ┆   ┆        ┆        ┆        ┆        │
│ 2026-04-20   ┆ 32    ┆ 2            ┆ 853           ┆ … ┆ 249.22 ┆ 249.26 ┆ 10998  ┆ AMZN   │
│ 09:30:01 EDT ┆       ┆              ┆               ┆   ┆        ┆        ┆        ┆        │
│ 2026-04-20   ┆ 32    ┆ 2            ┆ 853           ┆ … ┆ 249.06 ┆ 249.57 ┆ 23728  ┆ AMZN   │
│ 09:30:02 EDT ┆       ┆              ┆               ┆   ┆        ┆        ┆        ┆        │
│ 2026-04-20   ┆ 32    ┆ 2            ┆ 853           ┆ … ┆ 249.53 ┆ 249.78 ┆ 6099   ┆ AMZN   │
│ 09:30:03 EDT ┆       ┆              ┆               ┆   ┆        ┆        ┆        ┆        │
│ 2026-04-20   ┆ 32    ┆ 2            ┆ 853           ┆ … ┆ 249.63 ┆ 249.86 ┆ 8292   ┆ AMZN   │
│ 09:30:04 EDT ┆       ┆              ┆               ┆   ┆        ┆        ┆        ┆        │
└──────────────┴───────┴──────────────┴───────────────┴───┴────────┴────────┴────────┴────────┘